import { cx } from "cva";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { Navbar } from "@/components/layout";
import { AuthProvider } from "@/components/providers";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <AuthProvider>
      <html lang="en" className="bg-gradient-to-b from-slate-900 to-slate-950">
        <body className={cx(inter.className, "min-h-screen")}>
          <Navbar />
          <main className="prose prose-invert mx-auto max-w-7xl p-4 py-8">{children}</main>
        </body>
      </html>
    </AuthProvider>
  );
}
